const TYPES = {
  UserModel: Symbol.for("UserModel"),
  AdminModel: Symbol.for("AdminModel"),
  FriendRequestModel: Symbol.for("FriendRequestModel"),
  ClubModel: Symbol.for("ClubModel"),
  GameModel: Symbol.for("GameModel"),
  UserRepository: Symbol.for("UserRepository"),
  AdminRepository: Symbol.for("AdminRepository"),
  FriendRepository: Symbol.for("FriendRepository"),
  ClubRepository: Symbol.for("ClubRepository"),
  GameRepository: Symbol.for("GameRepository"),
  UserService: Symbol.for("UserService"),
  AdminService: Symbol.for("AdminService"),
  FriendService: Symbol.for("FriendService"),
  ClubService: Symbol.for("ClubService"),
  GameService: Symbol.for("GameService"),
  TokenService: Symbol.for("TokenService"),
  MailService: Symbol.for("MailService"),
  UserController: Symbol.for("UserController"),
  AdminController: Symbol.for("AdminController"),
  FriendController: Symbol.for("FriendController"),
  ClubController: Symbol.for("ClubController"),
  GameController: Symbol.for("GameController"),
};

export default TYPES;