import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/lib/providers/QueryProvider";
import { Toaster } from "@/components/ui/sonner";
import ClientSocketInitializer from "@/components/ClientSocketInitializer";
import ClientNavbarWrapper from "@/components/ClientNavbarWrapper";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=clash-display@400,500,600,700&f[]=stardom@400&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" type="image/svg+xml" href="/test-favicon.svg" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} font-sans antialiased`}>
        <QueryProvider>
          <ClientSocketInitializer />
          <ClientNavbarWrapper />
          {children}
        </QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
